pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
               git branch: 'main', url: 'https://github.com/Ml1727/devops-ultimate.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'sudo docker build -t devops-app -f terraform/monitoring/Dockerfile .'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                sudo docker rm -f devops-container || true
                sudo docker run -d -p 5000:5000 --name devops-container devops-app
                '''
            }
        }
    }
}
